preload = ~/.config/hypr/lightbg.jpg
# Wallpapers
wallpaper {
    monitor = DP-1
    path = /home/andrei/.config/hypr/lightbg.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/andrei/.config/hypr/lightbg.jpg
    fit_mode = cover
}
